# Generated by Django 5.0.6 on 2024-05-31 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patient_user_id_therapist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_photo',
            field=models.ImageField(default='fake', upload_to='id_photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preferences',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
    ]
