# Generated by Django 5.0.6 on 2024-05-31 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='patient',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='myapp.training')),
            ],
        ),
    ]
