# Generated by Django 5.0.6 on 2024-05-31 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_training_patient_alter_training_training_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='patient',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
    ]
