# Generated by Django 5.0.6 on 2024-05-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_training_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='patient',
        ),
    ]
